---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-datanode-cluster
spec:
  selector:
    matchLabels:
      app: hadoop-datanode
  replicas: 3
  template:
    metadata:
      labels:
        app: hadoop-datanode
    spec:
      containers:
        - name: hadoop-datanode
          image: nicolas2lee/hadoop
          ports:
            - containerPort: 2181
          command:
            - bash
            - "-c"
            - "/opt/hadoop-3.1.2/bin/hdfs datanode -fs hdfs://10.96.148.72:9000"
---
#no need to expose to service
#apiVersion: v1
#kind: Service
#metadata:
#  name: hadoop-datanode
#  labels:
#    app: hadoop-datanode
#spec:
#  ports:
#    - name: client-port
#      port: 2181
#      protocol: TCP
#    - name: web-ui-port
#      port: 50075
#      protocol: TCP
#  selector:
#    app: hadoop-datanode

